version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./html/first/:/var/www/html/
        extra_hosts:
          - "first.loc:127.0.0.1"
        hostname: first.loc
        domainname: loc 
        links:
            - db:db
        networks:
            - default
    db:
        image: mysql:5.7
        container_name: db
        ports: 
            - "3306:3306"
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_DATABASE: yii2_learn
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: Ghjuth67
            MYSQL_ROOT_PASSWORD: test
        volumes:
            #- ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8002:80
        environment:
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: Ghjuth67
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
